### ISSUE TITLE
no-use-before-define and Sonar Analysis results clashes

### ISSUE THREAD

**Issue by bcinarli** [adidas/js-linter-configs#12]
**Node/npm version(s)**: > 8

**Package(s) version(s)**: 1.2.1

**Rule name(s)**: `no-use-before-define`

**What does it provide?**: This rule checks if function/variable called before is it defined in order prevent hoisting.

**Does it conflict with any other rule?**: no

**Use case example**: Currently it is set to off, but in our SonarAnalysis results, it gives an error. Do you think we need to set this as `error` by default or overwrite it in our project?

**Comment by RecuencoJones** [comment]
Hi @bcinarli, when we thought about publishing the linter configurations, we "relaxed" some rules a bit for them to be easier to adopt in projects. This is one of those rules.

Sonar complements these rules and is more restrictive, most of our projects and colleagues already code with "define before use" in mind, if you want to force it, I would definitely set it in the project.
