### ISSUE TITLE
Update in certain rules in-order to reduce overwrites

### ISSUE THREAD

**Issue by bcinarli** [adidas/js-linter-configs#3]
**Node/npm version(s)**: > 8

**Package(s) version(s)**: 1.0.1

**Rule name(s)**: `no-invalid-this`, `no-extra-parens`, `radix`

**Requirements (package specific version, plugins, etc.)**: N/A

**What does it provide?**: 
`no-invalid-this` rule with the current setup, triggers an error when we are using `this` in an arrow function inside a React class. 

`no-extra-parens` clashes with `no-mixed-operators` rule with mathematical calculations. 

`radix` rule with the current setup always expecting radix even for base 10 in `parseInt` where we in almost use the base 10 as default.

**Does it conflict with any other rule?**: N/A

**Use case example**:

for `no-invalid-this`, following code triggers an error.

``` js
handleClickFullAccount = (e: Event) => {
    e.preventDefault();
    this.setState(newState);
};
```

for `no-extra-parens` with `no-mixed-operators` rule, following code triggers an error

``` js
// triggers `no-mixed-operators` error
const top = window.screenTop + ( window.outerHeight - 400 ) / 2;

// triggers `no-extra-parens` error
const top = window.screenTop + (( window.outerHeight - 400 ) / 2);
```

for `radix`, the following code triggers an error

``` js
parseInt('50%');

// expected code
parseInt('50%', 10);
```

**Comment by bcinarli** [comment]
As @moelders suggested, for now, I discarded the `no-invalid-this` rule update.

**Comment by moelders** [comment]
The changes have been approved. Thank you @bcinarli!
