### ISSUE TITLE
Remove the newly added `jsx-space-before-closing` rule

### ISSUE THREAD

**Issue by ghost** [adidas/js-linter-configs#8]
**Package(s) version(s)**: eslint-config-adidas-react 1.1.0

**Rule name(s)**: react/jsx-space-before-closing

**Reasoning to disable the rule(s)**: It's a deprecated rule and it contradicts the `react/jsx-tag-spacing` rule

**Comment by moelders** [comment]
Thanks @guidobonnet, we will remove it as soon as possible and check other rules to improve the configuration.

**Comment by moelders** [comment]
Issue fixed: `eslint-config-adidas-react@1.1.1`.
